services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  obrio_db:
    image: postgres
    container_name: obrio_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: obrio_app
      POSTGRES_PASSWORD: obrio_app_password
    volumes:
      - obrio_postgres_volume:/var/lib/postgresql/data
    configs:
      - source: db.initializer.sql
        target: /docker-entrypoint-initdb.d/db.initializer.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: obrio_pgadmin
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1
    volumes:
      - obrio_pgadmin_volume:/var/lib/pgadmin

volumes:
  obrio_postgres_volume:
  obrio_pgadmin_volume:

configs:
  db.initializer.sql:
    content: |
      CREATE DATABASE user_service;
