services:
  obrio_db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: obrio_app
      POSTGRES_PASSWORD: obrio_app_password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    configs:
      - source: db.initializer.sql
        target: /docker-entrypoint-initdb.d/db.initializer.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

configs:
  db.initializer.sql:
    content: |
      CREATE DATABASE user_service;
      CREATE DATABASE notification_service;
